name: test_ext
description: The extensions for test
version: 0.0.2
author: yongjhih@gmail.com
homepage: https://github.com/yongjhih/flutter_ext

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  test: ^1.16.0
