name: datex
description: The extensions for DateTime/Duration
version: 0.0.2
author: yongjhih@gmail.com
homepage: https://github.com/yongjhih/flutter_ext

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  time: ^1.2.0
  #dartx: ^0.3.0
  dartx:
    git:
      url: https://github.com/yongjhih/dartx.git
      ref: 17b10bb50a6fa6865fc58147b4063f77bcbe66f9
  intl: ^0.16.0

dev_dependencies:
  test: ^1.9.2
  test_ext: ^0.0.1
