name: datex
description: The extensions for DateTime/Duration
version: 0.0.3
author: yongjhih@gmail.com
homepage: https://github.com/yongjhih/flutter_ext

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  time: ^2.0.0
  dartx: ^1.1.0
  intl: ^0.17.0

dev_dependencies:
  test: ^1.21.0
  #test_ext: ^0.0.1
