name: datex
description: The extensions for DateTime/Duration
version: 0.0.2
author: yongjhih@gmail.com
homepage: https://github.com/yongjhih/flutter_ext

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  time: ^1.2.0
  #dartx: ^0.3.0
  dartx:
    git:
      url: https://github.com/yongjhih/dartx.git
      ref: 47cdd3fa643c37c0502e84bbfd9ad98b67c280d9
  intl: ^0.16.0

dev_dependencies:
  test: ^1.9.2
  test_ext: ^0.0.1
