name: rxdartx
description: A new Flutter package project.
version: 0.0.1
author: yongjhih@gmail.com
homepage: https://github.com/yongjhih/flutter_ext

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  rxdart: ^0.23.0

dev_dependencies:
  test: ^1.9.2
~ pedantic: ^1.8.0
