name: testx
description: The extensions for test
version: 0.0.1
author: yongjhih@gmail.com
homepage: https://github.com/yongjhih/flutter_ext

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  test: ^1.9.2

dev_dependencies:
  test: ^1.9.2
